In [1]:
import numpy as np
import pandas as pd
from datetime import datetime 
import csv 
import matplotlib.pyplot as plt
from datetime import date
from datetime import time

In [2]:
def convertTimeStamp(string):
    """Converts a string to a datetime object.
    """
    time = datetime.strptime(string,'%m/%d/%Y %I:%M:%S %p') #Accepts time string, converts it to datetime object.
    return time
    
def elapsedTime(filepath):
    """
        Accepts a csv file as input, returns elapsed time between Created Date and Service Date.
        Data from: https://data.lacity.org/A-Well-Run-City/MyLA311-Service-Request-Data-2019/pvft-t768
    """
    dataframe = pd.read_csv(filepath)
    dataframe = dataframe.dropna()
    
    #filter dateset to CreatedDate and ServiceDate columns
    created_df = dataframe['CreatedDate'].dropna().apply(convertTimeStamp, 0) #apply convertTimeStamp to CreatedDate
    Service_df = dataframe['ServiceDate'].dropna().apply(convertTimeStamp, 0) #apply convertTimeStamp to ServiceDate
    
    #create elapsedTime column
    elapsed_df = Service_df - created_df #calculate the difference in the values in CreatedDate and ServiceDate
    dataframe.insert(3, "ElapsedTime", elapsed_df) #create column ElapsedTime with dataframe elapsed_df into dataframe dataframe
    df1 = dataframe[['CreatedDate', 'ServiceDate', 'ElapsedTime']]

    
    return df1

In [3]:
elapsedTime(r"C:\Users\hanaa\Downloads\MyLA311_Service_Request_Data_2019.csv")

C:\Users\hanaa\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3249: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

                    CreatedDate             ServiceDate       ElapsedTime
6        01/01/2019 12:37:00 AM  04/02/2019 02:37:00 PM  91 days 14:00:00
17       01/01/2019 01:19:00 AM  06/04/2019 12:00:00 AM 153 days 22:41:00
32       01/01/2019 02:43:00 AM  01/02/2019 04:10:00 PM   1 days 13:27:00
39       01/01/2019 03:56:00 AM  04/02/2019 02:27:00 PM  91 days 10:31:00
42       01/01/2019 06:53:00 AM  01/02/2019 09:56:00 AM   1 days 03:03:00
...                         ...                     ...               ...
1308068  12/31/2019 10:12:00 PM  01/02/2020 12:00:00 AM   1 days 01:48:00
1308083  12/31/2019 11:11:00 PM  01/18/2020 10:13:00 AM  17 days 11:02:00
1308084  12/31/2019 11:13:00 PM  01/02/2020 03:20:00 PM   1 days 16:07:00
1308086  12/31/2019 11:19:00 PM  01/02/2020 03:17:00 PM   1 days 15:58:00
1308087  12/31/2019 11:25:00 PM  01/17/2020 12:00:00 AM  16 days 00:35:00

[80467 rows x 3 columns]